/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "error": "#ba1a1a",
        "on-surface": "#0b1c30",
        "secondary": "#006a61",
        "on-primary-fixed": "#00174b",
        "on-surface-variant": "#434655",
        "surface-container-low": "#eff4ff",
        "outline": "#737686",
        "on-error": "#ffffff",
        "surface-dim": "#cbdbf5",
        "outline-variant": "#c3c6d7",
        "primary-container": "#2563eb",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed": "#2a1700",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#00201d",
        "inverse-surface": "#213145",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#6bd8cb",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffeedd",
        "on-primary": "#ffffff",
        "tertiary": "#784b00",
        "on-secondary": "#ffffff",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#0053db",
        "primary": "#004ac6",
        "tertiary-fixed": "#ffddb8",
        "on-error-container": "#93000a",
        "on-secondary-container": "#006f66",
        "secondary-container": "#86f2e4",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed-variant": "#005049",
        "on-primary-container": "#eeefff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#996100",
        "on-background": "#0b1c30",
        "inverse-primary": "#b4c5ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#89f5e7",
        "background": "#f8f9ff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-max": "1280px",
        "stack-sm": "8px",
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "stack-md": "16px",
        "stack-lg": "32px"
      },
      "fontFamily": {
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"]
      },
    },
  },
  plugins: [],
}
